#!/usr/bin/sh

HEADER="################"
BACKUP_DISABLED_MESSAGE=$(printf 'local backup disabled.\nSet GIT_LOCAL_BACKUP_DIR env variable to enable it')

if [ -z "$GIT_LOCAL_BACKUP_DIR" ]; then
    printf '\n%s\n%s\n%s\n\n' "$HEADER" "$BACKUP_DISABLED_MESSAGE" "$HEADER"
    exit 0
fi

REPO_NAME=$(basename "$(git rev-parse --show-toplevel)")
BACKUP_FILE=$REPO_NAME-$(date '+%Y%m%d%H%M%S')
BACKUP_FULL_PATH=$GIT_LOCAL_BACKUP_DIR/$BACKUP_FILE
BACKUP_SUCCESSFUL_MESSAGE=$(printf 'backup created: %s' "$BACKUP_FULL_PATH")

git bundle create "$BACKUP_FULL_PATH" --all
printf '\n%s\n%s\n%s\n\n' "$HEADER" "$BACKUP_SUCCESSFUL_MESSAGE" "$HEADER"
